import Head from 'next/head';

import BasicCard from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rak Bank Latest Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicCard />
    </>
  );
}
